### ISSUE TITLE
Serve the files

### ISSUE THREAD

**Issue by vise890** [vise890/dropwiki#1]
Given the folder structure on the LHS, the files should be available by `GET`ting at the URL at the RHS
```
Folder structure               || URL
.
├── bup.md                      # GET localhost:9000/bup
├── foo                            
│   ├── bar                       
│   │   ├── baz.md              # GET localhost:9000/foo/bar/baz.md
│   │   └── quux.md             # GET localhost:9000/foo/bar/quux.md
│   └── beep.md                 # GET localhost:9000/foo/beep.md
└── index.md                    # GET localhost:9000/index.md
```

`GET`ting a folder (e.g. `GET localhost:9000/`) should render the `index.md`, if any, or throw a `404`

**Comment by vise890** [comment]
> `GET`ting a folder (e.g. `GET localhost:9000/`) should render the `index.md`, if any, or throw a `404` 
are we ok with this behaviour?

**Comment by maxmcd** [comment]
Sounds great. Maybe accept `readme.md` as well? Kind of the `index` of the markdown world

**Comment by vise890** [comment]
yea, let's go for it. so in order it would look for:

- `README.md`
- `readme.md`
- `index.md`

?

**Comment by vise890** [comment]
hey, we're keeping the `.md` extensions in the URLs yea?

**Comment by vise890** [comment]
NOTE: this is being devved in #4

**Comment by vise890** [comment]
**NOTE:** the spiritual follower of this issue is #8
